// Code generated by "stringer -type EventType -trimprefix EVENT_"; DO NOT EDIT.

package sdl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EVENT_QUIT-256]
	_ = x[EVENT_WINDOW_PIXEL_SIZE_CHANGED-519]
	_ = x[EVENT_KEY_DOWN-768]
	_ = x[EVENT_KEY_UP-769]
	_ = x[EVENT_MOUSE_MOTION-1024]
	_ = x[EVENT_MOUSE_BUTTON_DOWN-1025]
	_ = x[EVENT_MOUSE_BUTTON_UP-1026]
	_ = x[EVENT_MOUSE_WHEEL-1027]
	_ = x[EVENT_GAMEPAD_AXIS_MOTION-1616]
	_ = x[EVENT_GAMEPAD_BUTTON_DOWN-1617]
	_ = x[EVENT_GAMEPAD_BUTTON_UP-1618]
	_ = x[EVENT_GAMEPAD_ADDED-1619]
	_ = x[EVENT_GAMEPAD_REMOVED-1620]
	_ = x[EVENT_GAMEPAD_REMAPPED-1621]
	_ = x[EVENT_GAMEPAD_TOUCHPAD_DOWN-1622]
	_ = x[EVENT_GAMEPAD_TOUCHPAD_MOTION-1623]
	_ = x[EVENT_GAMEPAD_TOUCHPAD_UP-1624]
	_ = x[EVENT_GAMEPAD_SENSOR_UPDATE-1625]
	_ = x[EVENT_GAMEPAD_UPDATE_COMPLETE-1626]
	_ = x[EVENT_GAMEPAD_STEAM_HANDLE_UPDATED-1627]
}

const (
	_EventType_name_0 = "QUIT"
	_EventType_name_1 = "WINDOW_PIXEL_SIZE_CHANGED"
	_EventType_name_2 = "KEY_DOWNKEY_UP"
	_EventType_name_3 = "MOUSE_MOTIONMOUSE_BUTTON_DOWNMOUSE_BUTTON_UPMOUSE_WHEEL"
	_EventType_name_4 = "GAMEPAD_AXIS_MOTIONGAMEPAD_BUTTON_DOWNGAMEPAD_BUTTON_UPGAMEPAD_ADDEDGAMEPAD_REMOVEDGAMEPAD_REMAPPEDGAMEPAD_TOUCHPAD_DOWNGAMEPAD_TOUCHPAD_MOTIONGAMEPAD_TOUCHPAD_UPGAMEPAD_SENSOR_UPDATEGAMEPAD_UPDATE_COMPLETEGAMEPAD_STEAM_HANDLE_UPDATED"
)

var (
	_EventType_index_2 = [...]uint8{0, 8, 14}
	_EventType_index_3 = [...]uint8{0, 12, 29, 44, 55}
	_EventType_index_4 = [...]uint8{0, 19, 38, 55, 68, 83, 99, 120, 143, 162, 183, 206, 234}
)

func (i EventType) String() string {
	switch {
	case i == 256:
		return _EventType_name_0
	case i == 519:
		return _EventType_name_1
	case 768 <= i && i <= 769:
		i -= 768
		return _EventType_name_2[_EventType_index_2[i]:_EventType_index_2[i+1]]
	case 1024 <= i && i <= 1027:
		i -= 1024
		return _EventType_name_3[_EventType_index_3[i]:_EventType_index_3[i+1]]
	case 1616 <= i && i <= 1627:
		i -= 1616
		return _EventType_name_4[_EventType_index_4[i]:_EventType_index_4[i+1]]
	default:
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
