// Code generated by "stringer -type GamepadButton -trimprefix GAMEPAD_BUTTON_"; DO NOT EDIT.

package sdl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GAMEPAD_BUTTON_SOUTH-0]
	_ = x[GAMEPAD_BUTTON_EAST-1]
	_ = x[GAMEPAD_BUTTON_WEST-2]
	_ = x[GAMEPAD_BUTTON_NORTH-3]
	_ = x[GAMEPAD_BUTTON_BACK-4]
	_ = x[GAMEPAD_BUTTON_START-6]
	_ = x[GAMEPAD_BUTTON_LEFT_STICK-7]
	_ = x[GAMEPAD_BUTTON_RIGHT_STICK-8]
	_ = x[GAMEPAD_BUTTON_LEFT_SHOULDER-9]
	_ = x[GAMEPAD_BUTTON_RIGHT_SHOULDER-10]
	_ = x[GAMEPAD_BUTTON_DPAD_UP-11]
	_ = x[GAMEPAD_BUTTON_DPAD_DOWN-12]
	_ = x[GAMEPAD_BUTTON_DPAD_LEFT-13]
	_ = x[GAMEPAD_BUTTON_DPAD_RIGHT-14]
	_ = x[GAMEPAD_BUTTON_RIGHT_PADDLE1-16]
	_ = x[GAMEPAD_BUTTON_LEFT_PADDLE1-17]
	_ = x[GAMEPAD_BUTTON_RIGHT_PADDLE2-18]
	_ = x[GAMEPAD_BUTTON_LEFT_PADDLE2-19]
}

const (
	_GamepadButton_name_0 = "SOUTHEASTWESTNORTHBACK"
	_GamepadButton_name_1 = "STARTLEFT_STICKRIGHT_STICKLEFT_SHOULDERRIGHT_SHOULDERDPAD_UPDPAD_DOWNDPAD_LEFTDPAD_RIGHT"
	_GamepadButton_name_2 = "RIGHT_PADDLE1LEFT_PADDLE1RIGHT_PADDLE2LEFT_PADDLE2"
)

var (
	_GamepadButton_index_0 = [...]uint8{0, 5, 9, 13, 18, 22}
	_GamepadButton_index_1 = [...]uint8{0, 5, 15, 26, 39, 53, 60, 69, 78, 88}
	_GamepadButton_index_2 = [...]uint8{0, 13, 25, 38, 50}
)

func (i GamepadButton) String() string {
	switch {
	case i <= 4:
		return _GamepadButton_name_0[_GamepadButton_index_0[i]:_GamepadButton_index_0[i+1]]
	case 6 <= i && i <= 14:
		i -= 6
		return _GamepadButton_name_1[_GamepadButton_index_1[i]:_GamepadButton_index_1[i+1]]
	case 16 <= i && i <= 19:
		i -= 16
		return _GamepadButton_name_2[_GamepadButton_index_2[i]:_GamepadButton_index_2[i+1]]
	default:
		return "GamepadButton(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
