// Code generated by "stringer -type GamepadType -trimprefix GAMEPAD_TYPE_"; DO NOT EDIT.

package sdl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GAMEPAD_TYPE_XBOX360-2]
	_ = x[GAMEPAD_TYPE_XBOXONE-3]
	_ = x[GAMEPAD_TYPE_PS3-4]
	_ = x[GAMEPAD_TYPE_PS4-5]
	_ = x[GAMEPAD_TYPE_PS5-6]
}

const _GamepadType_name = "XBOX360XBOXONEPS3PS4PS5"

var _GamepadType_index = [...]uint8{0, 7, 14, 17, 20, 23}

func (i GamepadType) String() string {
	i -= 2
	if i >= GamepadType(len(_GamepadType_index)-1) {
		return "GamepadType(" + strconv.FormatInt(int64(i+2), 10) + ")"
	}
	return _GamepadType_name[_GamepadType_index[i]:_GamepadType_index[i+1]]
}
