// Code generated by "stringer -type MouseButton -trimprefix BUTTON_"; DO NOT EDIT.

package sdl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BUTTON_LEFT-1]
	_ = x[BUTTON_MIDDLE-2]
	_ = x[BUTTON_RIGHT-3]
	_ = x[BUTTON_X1-4]
	_ = x[BUTTON_X2-5]
}

const _MouseButton_name = "LEFTMIDDLERIGHTX1X2"

var _MouseButton_index = [...]uint8{0, 4, 10, 15, 17, 19}

func (i MouseButton) String() string {
	i -= 1
	if i >= MouseButton(len(_MouseButton_index)-1) {
		return "MouseButton(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _MouseButton_name[_MouseButton_index[i]:_MouseButton_index[i+1]]
}
