// Code generated by "stringer -trimprefix Shape -type ShapeKind -output shape_kind_string.go"; DO NOT EDIT.

package physics

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ShapeSphere-1]
	_ = x[ShapeBox-2]
	_ = x[ShapeCylinder-3]
	_ = x[ShapeConvexHull-4]
	_ = x[ShapeMesh-5]
}

const _ShapeKind_name = "SphereBoxCylinderConvexHullMesh"

var _ShapeKind_index = [...]uint8{0, 6, 9, 17, 27, 31}

func (i ShapeKind) String() string {
	i -= 1
	if i < 0 || i >= ShapeKind(len(_ShapeKind_index)-1) {
		return "ShapeKind(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ShapeKind_name[_ShapeKind_index[i]:_ShapeKind_index[i+1]]
}
