// Code generated by "stringer -trimprefix CollisionGeometry -type CollisionGeometryKind -output collision_geometry_kind_string.go"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CollisionGeometrySphere-1]
	_ = x[CollisionGeometryBox-2]
	_ = x[CollisionGeometryCylinder-3]
	_ = x[CollisionGeometryFileBacked-4]
}

const _CollisionGeometryKind_name = "SphereBoxCylinderFileBacked"

var _CollisionGeometryKind_index = [...]uint8{0, 6, 9, 17, 27}

func (i CollisionGeometryKind) String() string {
	i -= 1
	if i < 0 || i >= CollisionGeometryKind(len(_CollisionGeometryKind_index)-1) {
		return "CollisionGeometryKind(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _CollisionGeometryKind_name[_CollisionGeometryKind_index[i]:_CollisionGeometryKind_index[i+1]]
}
