// Code generated by "stringer -trimprefix Geometry -type GeometryKind -output geometry_kind_string.go"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GeometrySphere-1]
	_ = x[GeometryBox-2]
	_ = x[GeometryCylinder-3]
	_ = x[GeometryFileBacked-4]
}

const _GeometryKind_name = "SphereBoxCylinderFileBacked"

var _GeometryKind_index = [...]uint8{0, 6, 9, 17, 27}

func (i GeometryKind) String() string {
	i -= 1
	if i < 0 || i >= GeometryKind(len(_GeometryKind_index)-1) {
		return "GeometryKind(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _GeometryKind_name[_GeometryKind_index[i]:_GeometryKind_index[i+1]]
}
