package main

import (
	"bytes"
	"flag"
	"go/format"
	"io"
	"log"
	"os"
)

var out = flag.String("o", "", "a")

type Generator interface {
	Gen(w io.Writer) error
}

func main() {
	flag.Parse()

	buf := new(bytes.Buffer)

	// TODO: specify package name on the command line
	buf.WriteString(header)

	// TODO: specify what to generate on the command line

	for _, generator := range []Generator{
		matGen{2, 2},
		matmulGen{2, 2, 2},

		matGen{3, 3},
		matmulGen{3, 3, 3},

		trmatGen{3},

		matGen{4, 4},
		matmulGen{4, 4, 4},

		matGen{2, 1},
		matmulGen{2, 2, 1},

		matGen{3, 1},
		matmulGen{3, 3, 1},

		matGen{4, 1},
		matmulGen{4, 4, 1},

		vecGen{2},
		vecGen{3},
		vecGen{4},

		affineGen{3},
	} {
		if err := generator.Gen(buf); err != nil {
			log.Fatal(err)
		}
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(*out, src, 0644); err != nil {
		log.Fatal(err)
	}
}

const header = `
// Code generated by _gen; DO NOT EDIT.

package gmath

import (
	"math"

	"golang.org/x/exp/constraints"
)
`
