// Code generated by "stringer -type InitFlags -trimprefix INIT_"; DO NOT EDIT.

package sdl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INIT_AUDIO-16]
	_ = x[INIT_VIDEO-32]
	_ = x[INIT_JOYSTICK-512]
	_ = x[INIT_HAPTIC-4096]
	_ = x[INIT_GAMEPAD-8192]
	_ = x[INIT_EVENTS-16384]
	_ = x[INIT_SENSOR-32768]
}

const (
	_InitFlags_name_0 = "AUDIO"
	_InitFlags_name_1 = "VIDEO"
	_InitFlags_name_2 = "JOYSTICK"
	_InitFlags_name_3 = "HAPTIC"
	_InitFlags_name_4 = "GAMEPAD"
	_InitFlags_name_5 = "EVENTS"
	_InitFlags_name_6 = "SENSOR"
)

func (i InitFlags) String() string {
	switch {
	case i == 16:
		return _InitFlags_name_0
	case i == 32:
		return _InitFlags_name_1
	case i == 512:
		return _InitFlags_name_2
	case i == 4096:
		return _InitFlags_name_3
	case i == 8192:
		return _InitFlags_name_4
	case i == 16384:
		return _InitFlags_name_5
	case i == 32768:
		return _InitFlags_name_6
	default:
		return "InitFlags(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
