// Code generated by "stringer -type GamepadAxis -trimprefix GAMEPAD_AXIS_"; DO NOT EDIT.

package sdl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GAMEPAD_AXIS_LEFTX-0]
	_ = x[GAMEPAD_AXIS_LEFTY-1]
	_ = x[GAMEPAD_AXIS_RIGHTX-2]
	_ = x[GAMEPAD_AXIS_RIGHTY-3]
	_ = x[GAMEPAD_AXIS_LEFT_TRIGGER-4]
	_ = x[GAMEPAD_AXIS_RIGHT_TRIGGER-5]
}

const _GamepadAxis_name = "LEFTXLEFTYRIGHTXRIGHTYLEFT_TRIGGERRIGHT_TRIGGER"

var _GamepadAxis_index = [...]uint8{0, 5, 10, 16, 22, 34, 47}

func (i GamepadAxis) String() string {
	if i >= GamepadAxis(len(_GamepadAxis_index)-1) {
		return "GamepadAxis(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GamepadAxis_name[_GamepadAxis_index[i]:_GamepadAxis_index[i+1]]
}
