// Code generated by "stringer -type Keycode -trimprefix K_"; DO NOT EDIT.

package sdl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[K_RETURN-13]
	_ = x[K_ESCAPE-27]
	_ = x[K_BACKSPACE-8]
	_ = x[K_TAB-9]
	_ = x[K_SPACE-32]
	_ = x[K_EXCLAIM-33]
	_ = x[K_DBLAPOSTROPHE-34]
	_ = x[K_HASH-35]
	_ = x[K_DOLLAR-36]
	_ = x[K_PERCENT-37]
	_ = x[K_AMPERSAND-38]
	_ = x[K_APOSTROPHE-39]
	_ = x[K_LEFTPAREN-40]
	_ = x[K_RIGHTPAREN-41]
	_ = x[K_ASTERISK-42]
	_ = x[K_PLUS-43]
	_ = x[K_COMMA-44]
	_ = x[K_MINUS-45]
	_ = x[K_PERIOD-46]
	_ = x[K_SLASH-47]
	_ = x[K_0-48]
	_ = x[K_1-49]
	_ = x[K_2-50]
	_ = x[K_3-51]
	_ = x[K_4-52]
	_ = x[K_5-53]
	_ = x[K_6-54]
	_ = x[K_7-55]
	_ = x[K_8-56]
	_ = x[K_9-57]
	_ = x[K_COLON-58]
	_ = x[K_SEMICOLON-59]
	_ = x[K_LESS-60]
	_ = x[K_EQUALS-61]
	_ = x[K_GREATER-62]
	_ = x[K_QUESTION-63]
	_ = x[K_AT-64]
	_ = x[K_LEFTBRACKET-91]
	_ = x[K_BACKSLASH-92]
	_ = x[K_RIGHTBRACKET-93]
	_ = x[K_CARET-94]
	_ = x[K_UNDERSCORE-95]
	_ = x[K_GRAVE-96]
	_ = x[K_A-97]
	_ = x[K_B-98]
	_ = x[K_C-99]
	_ = x[K_D-100]
	_ = x[K_E-101]
	_ = x[K_F-102]
	_ = x[K_G-103]
	_ = x[K_H-104]
	_ = x[K_I-105]
	_ = x[K_J-106]
	_ = x[K_K-107]
	_ = x[K_L-108]
	_ = x[K_M-109]
	_ = x[K_N-110]
	_ = x[K_O-111]
	_ = x[K_P-112]
	_ = x[K_Q-113]
	_ = x[K_R-114]
	_ = x[K_S-115]
	_ = x[K_T-116]
	_ = x[K_U-117]
	_ = x[K_V-118]
	_ = x[K_W-119]
	_ = x[K_X-120]
	_ = x[K_Y-121]
	_ = x[K_Z-122]
	_ = x[K_LEFTBRACE-123]
	_ = x[K_PIPE-124]
	_ = x[K_RIGHTBRACE-125]
	_ = x[K_TILDE-126]
	_ = x[K_DELETE-127]
	_ = x[K_PLUSMINUS-177]
	_ = x[K_CAPSLOCK-1073741881]
	_ = x[K_F1-1073741882]
	_ = x[K_F2-1073741883]
	_ = x[K_F3-1073741884]
	_ = x[K_F4-1073741885]
	_ = x[K_F5-1073741886]
	_ = x[K_F6-1073741887]
	_ = x[K_F7-1073741888]
	_ = x[K_F8-1073741889]
	_ = x[K_F9-1073741890]
	_ = x[K_F10-1073741891]
	_ = x[K_F11-1073741892]
	_ = x[K_F12-1073741893]
	_ = x[K_PRINTSCREEN-1073741894]
	_ = x[K_SCROLLLOCK-1073741895]
	_ = x[K_PAUSE-1073741896]
	_ = x[K_INSERT-1073741897]
	_ = x[K_HOME-1073741898]
	_ = x[K_PAGEUP-1073741899]
	_ = x[K_END-1073741901]
	_ = x[K_PAGEDOWN-1073741902]
	_ = x[K_RIGHT-1073741903]
	_ = x[K_LEFT-1073741904]
	_ = x[K_DOWN-1073741905]
	_ = x[K_UP-1073741906]
	_ = x[K_NUMLOCKCLEAR-1073741907]
	_ = x[K_KP_DIVIDE-1073741908]
	_ = x[K_KP_MULTIPLY-1073741909]
	_ = x[K_KP_MINUS-1073741910]
	_ = x[K_KP_PLUS-1073741911]
	_ = x[K_KP_ENTER-1073741912]
	_ = x[K_KP_1-1073741913]
	_ = x[K_KP_2-1073741914]
	_ = x[K_KP_3-1073741915]
	_ = x[K_KP_4-1073741916]
	_ = x[K_KP_5-1073741917]
	_ = x[K_KP_6-1073741918]
	_ = x[K_KP_7-1073741919]
	_ = x[K_KP_8-1073741920]
	_ = x[K_KP_9-1073741921]
	_ = x[K_KP_0-1073741922]
	_ = x[K_KP_PERIOD-1073741923]
	_ = x[K_APPLICATION-1073741925]
	_ = x[K_POWER-1073741926]
	_ = x[K_KP_EQUALS-1073741927]
	_ = x[K_F13-1073741928]
	_ = x[K_F14-1073741929]
	_ = x[K_F15-1073741930]
	_ = x[K_F16-1073741931]
	_ = x[K_F17-1073741932]
	_ = x[K_F18-1073741933]
	_ = x[K_F19-1073741934]
	_ = x[K_F20-1073741935]
	_ = x[K_F21-1073741936]
	_ = x[K_F22-1073741937]
	_ = x[K_F23-1073741938]
	_ = x[K_F24-1073741939]
	_ = x[K_EXECUTE-1073741940]
	_ = x[K_HELP-1073741941]
	_ = x[K_MENU-1073741942]
	_ = x[K_SELECT-1073741943]
	_ = x[K_STOP-1073741944]
	_ = x[K_AGAIN-1073741945]
	_ = x[K_UNDO-1073741946]
	_ = x[K_CUT-1073741947]
	_ = x[K_COPY-1073741948]
	_ = x[K_PASTE-1073741949]
	_ = x[K_FIND-1073741950]
	_ = x[K_MUTE-1073741951]
	_ = x[K_VOLUMEUP-1073741952]
	_ = x[K_VOLUMEDOWN-1073741953]
	_ = x[K_KP_COMMA-1073741957]
	_ = x[K_KP_EQUALSAS400-1073741958]
	_ = x[K_ALTERASE-1073741977]
	_ = x[K_SYSREQ-1073741978]
	_ = x[K_CANCEL-1073741979]
	_ = x[K_CLEAR-1073741980]
	_ = x[K_PRIOR-1073741981]
	_ = x[K_RETURN2-1073741982]
	_ = x[K_SEPARATOR-1073741983]
	_ = x[K_OUT-1073741984]
	_ = x[K_OPER-1073741985]
	_ = x[K_CLEARAGAIN-1073741986]
	_ = x[K_CRSEL-1073741987]
	_ = x[K_EXSEL-1073741988]
	_ = x[K_KP_00-1073742000]
	_ = x[K_KP_000-1073742001]
	_ = x[K_THOUSANDSSEPARATOR-1073742002]
	_ = x[K_DECIMALSEPARATOR-1073742003]
	_ = x[K_CURRENCYUNIT-1073742004]
	_ = x[K_CURRENCYSUBUNIT-1073742005]
	_ = x[K_KP_LEFTPAREN-1073742006]
	_ = x[K_KP_RIGHTPAREN-1073742007]
	_ = x[K_KP_LEFTBRACE-1073742008]
	_ = x[K_KP_RIGHTBRACE-1073742009]
	_ = x[K_KP_TAB-1073742010]
	_ = x[K_KP_BACKSPACE-1073742011]
	_ = x[K_KP_A-1073742012]
	_ = x[K_KP_B-1073742013]
	_ = x[K_KP_C-1073742014]
	_ = x[K_KP_D-1073742015]
	_ = x[K_KP_E-1073742016]
	_ = x[K_KP_F-1073742017]
	_ = x[K_KP_XOR-1073742018]
	_ = x[K_KP_POWER-1073742019]
	_ = x[K_KP_PERCENT-1073742020]
	_ = x[K_KP_LESS-1073742021]
	_ = x[K_KP_GREATER-1073742022]
	_ = x[K_KP_AMPERSAND-1073742023]
	_ = x[K_KP_DBLAMPERSAND-1073742024]
	_ = x[K_KP_VERTICALBAR-1073742025]
	_ = x[K_KP_DBLVERTICALBAR-1073742026]
	_ = x[K_KP_COLON-1073742027]
	_ = x[K_KP_HASH-1073742028]
	_ = x[K_KP_SPACE-1073742029]
	_ = x[K_KP_AT-1073742030]
	_ = x[K_KP_EXCLAM-1073742031]
	_ = x[K_KP_MEMSTORE-1073742032]
	_ = x[K_KP_MEMRECALL-1073742033]
	_ = x[K_KP_MEMCLEAR-1073742034]
	_ = x[K_KP_MEMADD-1073742035]
	_ = x[K_KP_MEMSUBTRACT-1073742036]
	_ = x[K_KP_MEMMULTIPLY-1073742037]
	_ = x[K_KP_MEMDIVIDE-1073742038]
	_ = x[K_KP_PLUSMINUS-1073742039]
	_ = x[K_KP_CLEAR-1073742040]
	_ = x[K_KP_CLEARENTRY-1073742041]
	_ = x[K_KP_BINARY-1073742042]
	_ = x[K_KP_OCTAL-1073742043]
	_ = x[K_KP_DECIMAL-1073742044]
	_ = x[K_KP_HEXADECIMAL-1073742045]
	_ = x[K_LCTRL-1073742048]
	_ = x[K_LSHIFT-1073742049]
	_ = x[K_LALT-1073742050]
	_ = x[K_LGUI-1073742051]
	_ = x[K_RCTRL-1073742052]
	_ = x[K_RSHIFT-1073742053]
	_ = x[K_RALT-1073742054]
	_ = x[K_RGUI-1073742055]
	_ = x[K_MODE-1073742081]
	_ = x[K_SLEEP-1073742082]
	_ = x[K_WAKE-1073742083]
	_ = x[K_CHANNEL_INCREMENT-1073742084]
	_ = x[K_CHANNEL_DECREMENT-1073742085]
	_ = x[K_MEDIA_PLAY-1073742086]
	_ = x[K_MEDIA_PAUSE-1073742087]
	_ = x[K_MEDIA_RECORD-1073742088]
	_ = x[K_MEDIA_FAST_FORWARD-1073742089]
	_ = x[K_MEDIA_REWIND-1073742090]
	_ = x[K_MEDIA_NEXT_TRACK-1073742091]
	_ = x[K_MEDIA_PREVIOUS_TRACK-1073742092]
	_ = x[K_MEDIA_STOP-1073742093]
	_ = x[K_MEDIA_EJECT-1073742094]
	_ = x[K_MEDIA_PLAY_PAUSE-1073742095]
	_ = x[K_MEDIA_SELECT-1073742096]
	_ = x[K_AC_NEW-1073742097]
	_ = x[K_AC_OPEN-1073742098]
	_ = x[K_AC_CLOSE-1073742099]
	_ = x[K_AC_EXIT-1073742100]
	_ = x[K_AC_SAVE-1073742101]
	_ = x[K_AC_PRINT-1073742102]
	_ = x[K_AC_PROPERTIES-1073742103]
	_ = x[K_AC_SEARCH-1073742104]
	_ = x[K_AC_HOME-1073742105]
	_ = x[K_AC_BACK-1073742106]
	_ = x[K_AC_FORWARD-1073742107]
	_ = x[K_AC_STOP-1073742108]
	_ = x[K_AC_REFRESH-1073742109]
	_ = x[K_AC_BOOKMARKS-1073742110]
	_ = x[K_SOFTLEFT-1073742111]
	_ = x[K_SOFTRIGHT-1073742112]
	_ = x[K_CALL-1073742113]
	_ = x[K_ENDCALL-1073742114]
}

const _Keycode_name = "BACKSPACETABRETURNESCAPESPACEEXCLAIMDBLAPOSTROPHEHASHDOLLARPERCENTAMPERSANDAPOSTROPHELEFTPARENRIGHTPARENASTERISKPLUSCOMMAMINUSPERIODSLASH0123456789COLONSEMICOLONLESSEQUALSGREATERQUESTIONATLEFTBRACKETBACKSLASHRIGHTBRACKETCARETUNDERSCOREGRAVEABCDEFGHIJKLMNOPQRSTUVWXYZLEFTBRACEPIPERIGHTBRACETILDEDELETEPLUSMINUSCAPSLOCKF1F2F3F4F5F6F7F8F9F10F11F12PRINTSCREENSCROLLLOCKPAUSEINSERTHOMEPAGEUPENDPAGEDOWNRIGHTLEFTDOWNUPNUMLOCKCLEARKP_DIVIDEKP_MULTIPLYKP_MINUSKP_PLUSKP_ENTERKP_1KP_2KP_3KP_4KP_5KP_6KP_7KP_8KP_9KP_0KP_PERIODAPPLICATIONPOWERKP_EQUALSF13F14F15F16F17F18F19F20F21F22F23F24EXECUTEHELPMENUSELECTSTOPAGAINUNDOCUTCOPYPASTEFINDMUTEVOLUMEUPVOLUMEDOWNKP_COMMAKP_EQUALSAS400ALTERASESYSREQCANCELCLEARPRIORRETURN2SEPARATOROUTOPERCLEARAGAINCRSELEXSELKP_00KP_000THOUSANDSSEPARATORDECIMALSEPARATORCURRENCYUNITCURRENCYSUBUNITKP_LEFTPARENKP_RIGHTPARENKP_LEFTBRACEKP_RIGHTBRACEKP_TABKP_BACKSPACEKP_AKP_BKP_CKP_DKP_EKP_FKP_XORKP_POWERKP_PERCENTKP_LESSKP_GREATERKP_AMPERSANDKP_DBLAMPERSANDKP_VERTICALBARKP_DBLVERTICALBARKP_COLONKP_HASHKP_SPACEKP_ATKP_EXCLAMKP_MEMSTOREKP_MEMRECALLKP_MEMCLEARKP_MEMADDKP_MEMSUBTRACTKP_MEMMULTIPLYKP_MEMDIVIDEKP_PLUSMINUSKP_CLEARKP_CLEARENTRYKP_BINARYKP_OCTALKP_DECIMALKP_HEXADECIMALLCTRLLSHIFTLALTLGUIRCTRLRSHIFTRALTRGUIMODESLEEPWAKECHANNEL_INCREMENTCHANNEL_DECREMENTMEDIA_PLAYMEDIA_PAUSEMEDIA_RECORDMEDIA_FAST_FORWARDMEDIA_REWINDMEDIA_NEXT_TRACKMEDIA_PREVIOUS_TRACKMEDIA_STOPMEDIA_EJECTMEDIA_PLAY_PAUSEMEDIA_SELECTAC_NEWAC_OPENAC_CLOSEAC_EXITAC_SAVEAC_PRINTAC_PROPERTIESAC_SEARCHAC_HOMEAC_BACKAC_FORWARDAC_STOPAC_REFRESHAC_BOOKMARKSSOFTLEFTSOFTRIGHTCALLENDCALL"

var _Keycode_map = map[Keycode]string{
	8:          _Keycode_name[0:9],
	9:          _Keycode_name[9:12],
	13:         _Keycode_name[12:18],
	27:         _Keycode_name[18:24],
	32:         _Keycode_name[24:29],
	33:         _Keycode_name[29:36],
	34:         _Keycode_name[36:49],
	35:         _Keycode_name[49:53],
	36:         _Keycode_name[53:59],
	37:         _Keycode_name[59:66],
	38:         _Keycode_name[66:75],
	39:         _Keycode_name[75:85],
	40:         _Keycode_name[85:94],
	41:         _Keycode_name[94:104],
	42:         _Keycode_name[104:112],
	43:         _Keycode_name[112:116],
	44:         _Keycode_name[116:121],
	45:         _Keycode_name[121:126],
	46:         _Keycode_name[126:132],
	47:         _Keycode_name[132:137],
	48:         _Keycode_name[137:138],
	49:         _Keycode_name[138:139],
	50:         _Keycode_name[139:140],
	51:         _Keycode_name[140:141],
	52:         _Keycode_name[141:142],
	53:         _Keycode_name[142:143],
	54:         _Keycode_name[143:144],
	55:         _Keycode_name[144:145],
	56:         _Keycode_name[145:146],
	57:         _Keycode_name[146:147],
	58:         _Keycode_name[147:152],
	59:         _Keycode_name[152:161],
	60:         _Keycode_name[161:165],
	61:         _Keycode_name[165:171],
	62:         _Keycode_name[171:178],
	63:         _Keycode_name[178:186],
	64:         _Keycode_name[186:188],
	91:         _Keycode_name[188:199],
	92:         _Keycode_name[199:208],
	93:         _Keycode_name[208:220],
	94:         _Keycode_name[220:225],
	95:         _Keycode_name[225:235],
	96:         _Keycode_name[235:240],
	97:         _Keycode_name[240:241],
	98:         _Keycode_name[241:242],
	99:         _Keycode_name[242:243],
	100:        _Keycode_name[243:244],
	101:        _Keycode_name[244:245],
	102:        _Keycode_name[245:246],
	103:        _Keycode_name[246:247],
	104:        _Keycode_name[247:248],
	105:        _Keycode_name[248:249],
	106:        _Keycode_name[249:250],
	107:        _Keycode_name[250:251],
	108:        _Keycode_name[251:252],
	109:        _Keycode_name[252:253],
	110:        _Keycode_name[253:254],
	111:        _Keycode_name[254:255],
	112:        _Keycode_name[255:256],
	113:        _Keycode_name[256:257],
	114:        _Keycode_name[257:258],
	115:        _Keycode_name[258:259],
	116:        _Keycode_name[259:260],
	117:        _Keycode_name[260:261],
	118:        _Keycode_name[261:262],
	119:        _Keycode_name[262:263],
	120:        _Keycode_name[263:264],
	121:        _Keycode_name[264:265],
	122:        _Keycode_name[265:266],
	123:        _Keycode_name[266:275],
	124:        _Keycode_name[275:279],
	125:        _Keycode_name[279:289],
	126:        _Keycode_name[289:294],
	127:        _Keycode_name[294:300],
	177:        _Keycode_name[300:309],
	1073741881: _Keycode_name[309:317],
	1073741882: _Keycode_name[317:319],
	1073741883: _Keycode_name[319:321],
	1073741884: _Keycode_name[321:323],
	1073741885: _Keycode_name[323:325],
	1073741886: _Keycode_name[325:327],
	1073741887: _Keycode_name[327:329],
	1073741888: _Keycode_name[329:331],
	1073741889: _Keycode_name[331:333],
	1073741890: _Keycode_name[333:335],
	1073741891: _Keycode_name[335:338],
	1073741892: _Keycode_name[338:341],
	1073741893: _Keycode_name[341:344],
	1073741894: _Keycode_name[344:355],
	1073741895: _Keycode_name[355:365],
	1073741896: _Keycode_name[365:370],
	1073741897: _Keycode_name[370:376],
	1073741898: _Keycode_name[376:380],
	1073741899: _Keycode_name[380:386],
	1073741901: _Keycode_name[386:389],
	1073741902: _Keycode_name[389:397],
	1073741903: _Keycode_name[397:402],
	1073741904: _Keycode_name[402:406],
	1073741905: _Keycode_name[406:410],
	1073741906: _Keycode_name[410:412],
	1073741907: _Keycode_name[412:424],
	1073741908: _Keycode_name[424:433],
	1073741909: _Keycode_name[433:444],
	1073741910: _Keycode_name[444:452],
	1073741911: _Keycode_name[452:459],
	1073741912: _Keycode_name[459:467],
	1073741913: _Keycode_name[467:471],
	1073741914: _Keycode_name[471:475],
	1073741915: _Keycode_name[475:479],
	1073741916: _Keycode_name[479:483],
	1073741917: _Keycode_name[483:487],
	1073741918: _Keycode_name[487:491],
	1073741919: _Keycode_name[491:495],
	1073741920: _Keycode_name[495:499],
	1073741921: _Keycode_name[499:503],
	1073741922: _Keycode_name[503:507],
	1073741923: _Keycode_name[507:516],
	1073741925: _Keycode_name[516:527],
	1073741926: _Keycode_name[527:532],
	1073741927: _Keycode_name[532:541],
	1073741928: _Keycode_name[541:544],
	1073741929: _Keycode_name[544:547],
	1073741930: _Keycode_name[547:550],
	1073741931: _Keycode_name[550:553],
	1073741932: _Keycode_name[553:556],
	1073741933: _Keycode_name[556:559],
	1073741934: _Keycode_name[559:562],
	1073741935: _Keycode_name[562:565],
	1073741936: _Keycode_name[565:568],
	1073741937: _Keycode_name[568:571],
	1073741938: _Keycode_name[571:574],
	1073741939: _Keycode_name[574:577],
	1073741940: _Keycode_name[577:584],
	1073741941: _Keycode_name[584:588],
	1073741942: _Keycode_name[588:592],
	1073741943: _Keycode_name[592:598],
	1073741944: _Keycode_name[598:602],
	1073741945: _Keycode_name[602:607],
	1073741946: _Keycode_name[607:611],
	1073741947: _Keycode_name[611:614],
	1073741948: _Keycode_name[614:618],
	1073741949: _Keycode_name[618:623],
	1073741950: _Keycode_name[623:627],
	1073741951: _Keycode_name[627:631],
	1073741952: _Keycode_name[631:639],
	1073741953: _Keycode_name[639:649],
	1073741957: _Keycode_name[649:657],
	1073741958: _Keycode_name[657:671],
	1073741977: _Keycode_name[671:679],
	1073741978: _Keycode_name[679:685],
	1073741979: _Keycode_name[685:691],
	1073741980: _Keycode_name[691:696],
	1073741981: _Keycode_name[696:701],
	1073741982: _Keycode_name[701:708],
	1073741983: _Keycode_name[708:717],
	1073741984: _Keycode_name[717:720],
	1073741985: _Keycode_name[720:724],
	1073741986: _Keycode_name[724:734],
	1073741987: _Keycode_name[734:739],
	1073741988: _Keycode_name[739:744],
	1073742000: _Keycode_name[744:749],
	1073742001: _Keycode_name[749:755],
	1073742002: _Keycode_name[755:773],
	1073742003: _Keycode_name[773:789],
	1073742004: _Keycode_name[789:801],
	1073742005: _Keycode_name[801:816],
	1073742006: _Keycode_name[816:828],
	1073742007: _Keycode_name[828:841],
	1073742008: _Keycode_name[841:853],
	1073742009: _Keycode_name[853:866],
	1073742010: _Keycode_name[866:872],
	1073742011: _Keycode_name[872:884],
	1073742012: _Keycode_name[884:888],
	1073742013: _Keycode_name[888:892],
	1073742014: _Keycode_name[892:896],
	1073742015: _Keycode_name[896:900],
	1073742016: _Keycode_name[900:904],
	1073742017: _Keycode_name[904:908],
	1073742018: _Keycode_name[908:914],
	1073742019: _Keycode_name[914:922],
	1073742020: _Keycode_name[922:932],
	1073742021: _Keycode_name[932:939],
	1073742022: _Keycode_name[939:949],
	1073742023: _Keycode_name[949:961],
	1073742024: _Keycode_name[961:976],
	1073742025: _Keycode_name[976:990],
	1073742026: _Keycode_name[990:1007],
	1073742027: _Keycode_name[1007:1015],
	1073742028: _Keycode_name[1015:1022],
	1073742029: _Keycode_name[1022:1030],
	1073742030: _Keycode_name[1030:1035],
	1073742031: _Keycode_name[1035:1044],
	1073742032: _Keycode_name[1044:1055],
	1073742033: _Keycode_name[1055:1067],
	1073742034: _Keycode_name[1067:1078],
	1073742035: _Keycode_name[1078:1087],
	1073742036: _Keycode_name[1087:1101],
	1073742037: _Keycode_name[1101:1115],
	1073742038: _Keycode_name[1115:1127],
	1073742039: _Keycode_name[1127:1139],
	1073742040: _Keycode_name[1139:1147],
	1073742041: _Keycode_name[1147:1160],
	1073742042: _Keycode_name[1160:1169],
	1073742043: _Keycode_name[1169:1177],
	1073742044: _Keycode_name[1177:1187],
	1073742045: _Keycode_name[1187:1201],
	1073742048: _Keycode_name[1201:1206],
	1073742049: _Keycode_name[1206:1212],
	1073742050: _Keycode_name[1212:1216],
	1073742051: _Keycode_name[1216:1220],
	1073742052: _Keycode_name[1220:1225],
	1073742053: _Keycode_name[1225:1231],
	1073742054: _Keycode_name[1231:1235],
	1073742055: _Keycode_name[1235:1239],
	1073742081: _Keycode_name[1239:1243],
	1073742082: _Keycode_name[1243:1248],
	1073742083: _Keycode_name[1248:1252],
	1073742084: _Keycode_name[1252:1269],
	1073742085: _Keycode_name[1269:1286],
	1073742086: _Keycode_name[1286:1296],
	1073742087: _Keycode_name[1296:1307],
	1073742088: _Keycode_name[1307:1319],
	1073742089: _Keycode_name[1319:1337],
	1073742090: _Keycode_name[1337:1349],
	1073742091: _Keycode_name[1349:1365],
	1073742092: _Keycode_name[1365:1385],
	1073742093: _Keycode_name[1385:1395],
	1073742094: _Keycode_name[1395:1406],
	1073742095: _Keycode_name[1406:1422],
	1073742096: _Keycode_name[1422:1434],
	1073742097: _Keycode_name[1434:1440],
	1073742098: _Keycode_name[1440:1447],
	1073742099: _Keycode_name[1447:1455],
	1073742100: _Keycode_name[1455:1462],
	1073742101: _Keycode_name[1462:1469],
	1073742102: _Keycode_name[1469:1477],
	1073742103: _Keycode_name[1477:1490],
	1073742104: _Keycode_name[1490:1499],
	1073742105: _Keycode_name[1499:1506],
	1073742106: _Keycode_name[1506:1513],
	1073742107: _Keycode_name[1513:1523],
	1073742108: _Keycode_name[1523:1530],
	1073742109: _Keycode_name[1530:1540],
	1073742110: _Keycode_name[1540:1552],
	1073742111: _Keycode_name[1552:1560],
	1073742112: _Keycode_name[1560:1569],
	1073742113: _Keycode_name[1569:1573],
	1073742114: _Keycode_name[1573:1580],
}

func (i Keycode) String() string {
	if str, ok := _Keycode_map[i]; ok {
		return str
	}
	return "Keycode(" + strconv.FormatInt(int64(i), 10) + ")"
}
