//go:build ignore

package main

import (
	"bytes"
	"flag"
	"go/format"
	"os"
	"text/template"
)

var out = flag.String("o", "", "a")

var args struct {
	Package string
	D       int64
}

func init() {
	args.Package = "geometry"
	flag.Int64Var(&args.D, "D", -1, "a")
}

func main() {
	flag.Parse()

	buf := new(bytes.Buffer)
	tmpl.Execute(buf, &args)
	src, _ := format.Source(buf.Bytes())
	os.WriteFile(*out, src, 0644)
}

var tmpl = template.Must(template.New("").Parse(`
// Code generated by gen_vec.go; DO NOT EDIT.

package {{.Package}}

import (
	"math"

	"golang.org/x/exp/constraints"
)

{{- $gvecD := printf "gvec%d" .D}}

type {{$gvecD}}[T constraints.Float] [{{.D}}]T

// TODO: rename to Splat?
func {{$gvecD}}Broadcast[T constraints.Float](x T) {{$gvecD}}[T] {
	return {{$gvecD}}[T]{
		{{- range .D}}
		x,
		{{- end}}
	}
}

// Or Vec{{.D}}Convert?
func ConvertVec{{.D}}[T, U constraints.Float](a {{$gvecD}}[U]) {{$gvecD}}[T] {
	return {{$gvecD}}[T]{
		{{- range .D}}
		T(a[{{.}}]),
		{{- end}}
	}
}

func (a {{$gvecD}}[T]) Add(b {{$gvecD}}[T]) {{$gvecD}}[T] {
	return {{$gvecD}}[T]{
		{{- range .D}}
		a[{{.}}] + b[{{.}}],
		{{- end}}
	}
}

func (a {{$gvecD}}[T]) Sub(b {{$gvecD}}[T]) {{$gvecD}}[T] {
	return {{$gvecD}}[T]{
		{{- range .D}}
		a[{{.}}] - b[{{.}}],
		{{- end}}
	}
}

func (a {{$gvecD}}[T]) Scale(lambda T) {{$gvecD}}[T] {
	return {{$gvecD}}[T]{
		{{- range .D}}
		lambda * a[{{.}}],
		{{- end}}
	}
}

func (a {{$gvecD}}[T]) Dot(b {{$gvecD}}[T]) T {
	return 0 {{- range .D}} + a[{{.}}] * b[{{.}}] {{- end}}
}

func (a {{$gvecD}}[T]) LengthSq() T {
	return a.Dot(a)
}

func (a {{$gvecD}}[T]) Length() T {
	return T(math.Sqrt(float64(a.LengthSq())))
}

// TODO: simplify this so that it's just an ordinary normalize pls
func (a {{$gvecD}}[T]) NormalizedOr(b {{$gvecD}}[T]) {{$gvecD}}[T] {
	norm := a.Length()
	if norm == 0 {
		return b
	}
	return {{$gvecD}}[T]{
		{{- range .D}}
		a[{{.}}] / norm,
		{{- end}}
	}
}

func (a {{$gvecD}}[T]) Lerp(b {{$gvecD}}[T], t T) {{$gvecD}}[T] {
	return {{$gvecD}}[T]{
		{{- range .D}}
		lerp(a[{{.}}], b[{{.}}], t),
		{{- end}}
	}
}
`))
