// Code generated by gen_vec.go; DO NOT EDIT.

package geometry

import (
	"math"

	"golang.org/x/exp/constraints"
)

type gvec2[T constraints.Float] [2]T

func gvec2Ones[T constraints.Float]() gvec2[T] {
	return gvec2[T]{
		1,
		1,
	}
}

func Vec2Convert[To, From constraints.Float](a gvec2[From]) gvec2[To] {
	return gvec2[To]{
		To(a[0]),
		To(a[1]),
	}
}

func (a gvec2[T]) Add(b gvec2[T]) gvec2[T] {
	return gvec2[T]{
		a[0] + b[0],
		a[1] + b[1],
	}
}

func (a gvec2[T]) Sub(b gvec2[T]) gvec2[T] {
	return gvec2[T]{
		a[0] - b[0],
		a[1] - b[1],
	}
}

func (a gvec2[T]) Scale(lambda T) gvec2[T] {
	return gvec2[T]{
		lambda * a[0],
		lambda * a[1],
	}
}

func (a gvec2[T]) Dot(b gvec2[T]) T {
	return 0 + a[0]*b[0] + a[1]*b[1]
}

func (a gvec2[T]) LengthSq() T {
	return a.Dot(a)
}

func (a gvec2[T]) Length() T {
	return T(math.Sqrt(float64(a.LengthSq())))
}

// TODO: simplify this so that it's just an ordinary normalize pls
func (a gvec2[T]) NormalizedOr(b gvec2[T]) gvec2[T] {
	norm := a.Length()
	if norm == 0 {
		return b
	}
	return gvec2[T]{
		a[0] / norm,
		a[1] / norm,
	}
}

func (a gvec2[T]) Lerp(b gvec2[T], t T) gvec2[T] {
	return gvec2[T]{
		lerp(a[0], b[0], t),
		lerp(a[1], b[1], t),
	}
}
