// Code generated by gen_vec.go; DO NOT EDIT.

package geometry

import (
	"math"

	"golang.org/x/exp/constraints"
)

type gvec3[T constraints.Float] [3]T

func gvec3Ones[T constraints.Float]() gvec3[T] {
	return gvec3[T]{
		1,
		1,
		1,
	}
}

func Vec3Convert[To, From constraints.Float](a gvec3[From]) gvec3[To] {
	return gvec3[To]{
		To(a[0]),
		To(a[1]),
		To(a[2]),
	}
}

func (a gvec3[T]) Add(b gvec3[T]) gvec3[T] {
	return gvec3[T]{
		a[0] + b[0],
		a[1] + b[1],
		a[2] + b[2],
	}
}

func (a gvec3[T]) Sub(b gvec3[T]) gvec3[T] {
	return gvec3[T]{
		a[0] - b[0],
		a[1] - b[1],
		a[2] - b[2],
	}
}

func (a gvec3[T]) Scale(lambda T) gvec3[T] {
	return gvec3[T]{
		lambda * a[0],
		lambda * a[1],
		lambda * a[2],
	}
}

func (a gvec3[T]) Dot(b gvec3[T]) T {
	return 0 + a[0]*b[0] + a[1]*b[1] + a[2]*b[2]
}

func (a gvec3[T]) LengthSq() T {
	return a.Dot(a)
}

func (a gvec3[T]) Length() T {
	return T(math.Sqrt(float64(a.LengthSq())))
}

// TODO: simplify this so that it's just an ordinary normalize pls
func (a gvec3[T]) NormalizedOr(b gvec3[T]) gvec3[T] {
	norm := a.Length()
	if norm == 0 {
		return b
	}
	return gvec3[T]{
		a[0] / norm,
		a[1] / norm,
		a[2] / norm,
	}
}

func (a gvec3[T]) Lerp(b gvec3[T], t T) gvec3[T] {
	return gvec3[T]{
		lerp(a[0], b[0], t),
		lerp(a[1], b[1], t),
		lerp(a[2], b[2], t),
	}
}
