// Code generated by gen_vec.go; DO NOT EDIT.

package geometry

import (
	"math"

	"golang.org/x/exp/constraints"
)

type gvec4[T constraints.Float] [4]T

// TODO: rename to Splat?
func gvec4Broadcast[T constraints.Float](x T) gvec4[T] {
	return gvec4[T]{
		x,
		x,
		x,
		x,
	}
}

// Or Vec4Convert?
func ConvertVec4[T, U constraints.Float](a gvec4[U]) gvec4[T] {
	return gvec4[T]{
		T(a[0]),
		T(a[1]),
		T(a[2]),
		T(a[3]),
	}
}

func (a gvec4[T]) Add(b gvec4[T]) gvec4[T] {
	return gvec4[T]{
		a[0] + b[0],
		a[1] + b[1],
		a[2] + b[2],
		a[3] + b[3],
	}
}

func (a gvec4[T]) Sub(b gvec4[T]) gvec4[T] {
	return gvec4[T]{
		a[0] - b[0],
		a[1] - b[1],
		a[2] - b[2],
		a[3] - b[3],
	}
}

func (a gvec4[T]) Scale(lambda T) gvec4[T] {
	return gvec4[T]{
		lambda * a[0],
		lambda * a[1],
		lambda * a[2],
		lambda * a[3],
	}
}

func (a gvec4[T]) Dot(b gvec4[T]) T {
	return 0 + a[0]*b[0] + a[1]*b[1] + a[2]*b[2] + a[3]*b[3]
}

func (a gvec4[T]) LengthSq() T {
	return a.Dot(a)
}

func (a gvec4[T]) Length() T {
	return T(math.Sqrt(float64(a.LengthSq())))
}

// TODO: simplify this so that it's just an ordinary normalize pls
func (a gvec4[T]) NormalizedOr(b gvec4[T]) gvec4[T] {
	norm := a.Length()
	if norm == 0 {
		return b
	}
	return gvec4[T]{
		a[0] / norm,
		a[1] / norm,
		a[2] / norm,
		a[3] / norm,
	}
}

func (a gvec4[T]) Lerp(b gvec4[T], t T) gvec4[T] {
	return gvec4[T]{
		lerp(a[0], b[0], t),
		lerp(a[1], b[1], t),
		lerp(a[2], b[2], t),
		lerp(a[3], b[3], t),
	}
}
