// Code generated by "stringer -type A -trimprefix A"; DO NOT EDIT.

package material

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AStop-0]
	_ = x[ACopy32-1]
	_ = x[AConst32-2]
	_ = x[AFAddE8M23-3]
	_ = x[AFSubE8M23-4]
	_ = x[AFMulE8M23-5]
	_ = x[AFDivE8M23-6]
	_ = x[AFMinE8M23-7]
	_ = x[AFMaxE8M23-8]
	_ = x[AFFloorE8M23-9]
	_ = x[AFEqualE8M23-10]
	_ = x[AFLessOrEqualE8M23-11]
	_ = x[ACondSelect32-12]
	_ = x[ALoadParam-13]
	_ = x[ALoadAttr-14]
	_ = x[ALoadNormal-15]
}

const _A_name = "StopCopy32Const32FAddE8M23FSubE8M23FMulE8M23FDivE8M23FMinE8M23FMaxE8M23FFloorE8M23FEqualE8M23FLessOrEqualE8M23CondSelect32LoadParamLoadAttrLoadNormal"

var _A_index = [...]uint8{0, 4, 10, 17, 26, 35, 44, 53, 62, 71, 82, 93, 110, 122, 131, 139, 149}

func (i A) String() string {
	if i >= A(len(_A_index)-1) {
		return "A(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _A_name[_A_index[i]:_A_index[i+1]]
}
