// Code generated by "stringer -trimprefix PhysicsShape -type PhysicsShapeKind -output physics_shape_kind_string.go"; DO NOT EDIT.

package worldspawn

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PhysicsShapeSphere-1]
	_ = x[PhysicsShapeBox-2]
	_ = x[PhysicsShapeCylinder-3]
	_ = x[PhysicsShapeFileBacked-4]
}

const _PhysicsShapeKind_name = "SphereBoxCylinderFileBacked"

var _PhysicsShapeKind_index = [...]uint8{0, 6, 9, 17, 27}

func (i PhysicsShapeKind) String() string {
	i -= 1
	if i < 0 || i >= PhysicsShapeKind(len(_PhysicsShapeKind_index)-1) {
		return "PhysicsShapeKind(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _PhysicsShapeKind_name[_PhysicsShapeKind_index[i]:_PhysicsShapeKind_index[i+1]]
}
