// Code generated by _gen; DO NOT EDIT.

package gmath

import (
	"math"

	"golang.org/x/exp/constraints"
)

type Vec2[T constraints.Float] [2]T

type (
	Vec2f32 = Vec2[float32]
	Vec2f64 = Vec2[float64]
)

func (v Vec2[From]) Convert[To constraints.Float]() Vec2[To] {
	return Vec2[To]{
		To(v[0]),
		To(v[1]),
	}
}

func Vec2Ones[T constraints.Float]() Vec2[T] {
	return Vec2[T]{
		1,
		1,
	}
}

func (a Vec2[T]) Add(b Vec2[T]) Vec2[T] {
	return Vec2[T]{
		a[0] + b[0],
		a[1] + b[1],
	}
}

func (a Vec2[T]) Sub(b Vec2[T]) Vec2[T] {
	return Vec2[T]{
		a[0] - b[0],
		a[1] - b[1],
	}
}

func (a Vec2[T]) Scale(lambda T) Vec2[T] {
	return Vec2[T]{
		lambda * a[0],
		lambda * a[1],
	}
}

func (a Vec2[T]) Length() T {
	return T(math.Sqrt(float64(a.Dot(a))))
}

func (a Vec2[T]) Dot(b Vec2[T]) T {
	return 0 + a[0]*b[0] + a[1]*b[1]
}

func (v Vec2[T]) Normalize() Vec2[T] {
	lengthSqr := v.Dot(v)
	if !(lengthSqr > 0) {
		return Vec2[T]{}
	}
	length := T(math.Sqrt(float64(lengthSqr)))
	return Vec2[T]{
		v[0] / length,
		v[1] / length,
	}
}

// TODO: kill this
func (a Vec2[T]) Lerp(b Vec2[T], t T) Vec2[T] {
	return Vec2[T]{
		lerp(a[0], b[0], t),
		lerp(a[1], b[1], t),
	}
}

type Mat2x2[T constraints.Float] [2 * 2]T

type Mat2x2f32 = Mat2x2[float32]

func (M Mat2x2[From]) Convert[To constraints.Float]() Mat2x2[To] {
	var M2 Mat2x2[To]
	for i, v := range M {
		M2[i] = To(v)
	}
	return M2
}

func (A *Mat2x2[T]) Index(i, j int) *T {
	A_i := A[i*2:][:2]
	A_i_j := &A_i[j]
	return A_i_j
}

func Mat2x2One[T constraints.Float]() Mat2x2[T] {
	var I Mat2x2[T]
	*I.Index(0, 0) = 1
	*I.Index(1, 1) = 1
	return I
}

func Mat2x2Diag[T constraints.Float](d Vec2[T]) Mat2x2[T] {
	var D Mat2x2[T]
	*D.Index(0, 0) = d[0]
	*D.Index(1, 1) = d[1]
	return D
}

func (A Mat2x2[T]) Inv() Mat2x2[T] {
	panic("not implemented")
}

func (A Mat2x2[T]) Mul(B Mat2x2[T]) Mat2x2[T] {
	var AB Mat2x2[T]
	*AB.Index(0, 0) = 0 + *A.Index(0, 0)**B.Index(0, 0) + *A.Index(0, 1)**B.Index(1, 0)
	*AB.Index(0, 1) = 0 + *A.Index(0, 0)**B.Index(0, 1) + *A.Index(0, 1)**B.Index(1, 1)
	*AB.Index(1, 0) = 0 + *A.Index(1, 0)**B.Index(0, 0) + *A.Index(1, 1)**B.Index(1, 0)
	*AB.Index(1, 1) = 0 + *A.Index(1, 0)**B.Index(0, 1) + *A.Index(1, 1)**B.Index(1, 1)
	return AB
}

func (A Mat2x2[T]) Mulv(b Vec2[T]) Vec2[T] {
	var Ab Vec2[T]
	Ab[0] = 0 + *A.Index(0, 0)*b[0] + *A.Index(0, 1)*b[1]
	Ab[1] = 0 + *A.Index(1, 0)*b[0] + *A.Index(1, 1)*b[1]
	return Ab
}

type Vec3[T constraints.Float] [3]T

type (
	Vec3f32 = Vec3[float32]
	Vec3f64 = Vec3[float64]
)

func (v Vec3[From]) Convert[To constraints.Float]() Vec3[To] {
	return Vec3[To]{
		To(v[0]),
		To(v[1]),
		To(v[2]),
	}
}

func Vec3Ones[T constraints.Float]() Vec3[T] {
	return Vec3[T]{
		1,
		1,
		1,
	}
}

func (a Vec3[T]) Add(b Vec3[T]) Vec3[T] {
	return Vec3[T]{
		a[0] + b[0],
		a[1] + b[1],
		a[2] + b[2],
	}
}

func (a Vec3[T]) Sub(b Vec3[T]) Vec3[T] {
	return Vec3[T]{
		a[0] - b[0],
		a[1] - b[1],
		a[2] - b[2],
	}
}

func (a Vec3[T]) Scale(lambda T) Vec3[T] {
	return Vec3[T]{
		lambda * a[0],
		lambda * a[1],
		lambda * a[2],
	}
}

func (a Vec3[T]) Length() T {
	return T(math.Sqrt(float64(a.Dot(a))))
}

func (a Vec3[T]) Dot(b Vec3[T]) T {
	return 0 + a[0]*b[0] + a[1]*b[1] + a[2]*b[2]
}

func (v Vec3[T]) Normalize() Vec3[T] {
	lengthSqr := v.Dot(v)
	if !(lengthSqr > 0) {
		return Vec3[T]{}
	}
	length := T(math.Sqrt(float64(lengthSqr)))
	return Vec3[T]{
		v[0] / length,
		v[1] / length,
		v[2] / length,
	}
}

// TODO: kill this
func (a Vec3[T]) Lerp(b Vec3[T], t T) Vec3[T] {
	return Vec3[T]{
		lerp(a[0], b[0], t),
		lerp(a[1], b[1], t),
		lerp(a[2], b[2], t),
	}
}

type Mat3x3[T constraints.Float] [3 * 3]T

type Mat3x3f32 = Mat3x3[float32]

func (M Mat3x3[From]) Convert[To constraints.Float]() Mat3x3[To] {
	var M2 Mat3x3[To]
	for i, v := range M {
		M2[i] = To(v)
	}
	return M2
}

func (A *Mat3x3[T]) Index(i, j int) *T {
	A_i := A[i*3:][:3]
	A_i_j := &A_i[j]
	return A_i_j
}

func Mat3x3One[T constraints.Float]() Mat3x3[T] {
	var I Mat3x3[T]
	*I.Index(0, 0) = 1
	*I.Index(1, 1) = 1
	*I.Index(2, 2) = 1
	return I
}

func Mat3x3Diag[T constraints.Float](d Vec3[T]) Mat3x3[T] {
	var D Mat3x3[T]
	*D.Index(0, 0) = d[0]
	*D.Index(1, 1) = d[1]
	*D.Index(2, 2) = d[2]
	return D
}

func (A Mat3x3[T]) Inv() Mat3x3[T] {
	panic("not implemented")
}

func (A Mat3x3[T]) Mul(B Mat3x3[T]) Mat3x3[T] {
	var AB Mat3x3[T]
	*AB.Index(0, 0) = 0 + *A.Index(0, 0)**B.Index(0, 0) + *A.Index(0, 1)**B.Index(1, 0) + *A.Index(0, 2)**B.Index(2, 0)
	*AB.Index(0, 1) = 0 + *A.Index(0, 0)**B.Index(0, 1) + *A.Index(0, 1)**B.Index(1, 1) + *A.Index(0, 2)**B.Index(2, 1)
	*AB.Index(0, 2) = 0 + *A.Index(0, 0)**B.Index(0, 2) + *A.Index(0, 1)**B.Index(1, 2) + *A.Index(0, 2)**B.Index(2, 2)
	*AB.Index(1, 0) = 0 + *A.Index(1, 0)**B.Index(0, 0) + *A.Index(1, 1)**B.Index(1, 0) + *A.Index(1, 2)**B.Index(2, 0)
	*AB.Index(1, 1) = 0 + *A.Index(1, 0)**B.Index(0, 1) + *A.Index(1, 1)**B.Index(1, 1) + *A.Index(1, 2)**B.Index(2, 1)
	*AB.Index(1, 2) = 0 + *A.Index(1, 0)**B.Index(0, 2) + *A.Index(1, 1)**B.Index(1, 2) + *A.Index(1, 2)**B.Index(2, 2)
	*AB.Index(2, 0) = 0 + *A.Index(2, 0)**B.Index(0, 0) + *A.Index(2, 1)**B.Index(1, 0) + *A.Index(2, 2)**B.Index(2, 0)
	*AB.Index(2, 1) = 0 + *A.Index(2, 0)**B.Index(0, 1) + *A.Index(2, 1)**B.Index(1, 1) + *A.Index(2, 2)**B.Index(2, 1)
	*AB.Index(2, 2) = 0 + *A.Index(2, 0)**B.Index(0, 2) + *A.Index(2, 1)**B.Index(1, 2) + *A.Index(2, 2)**B.Index(2, 2)
	return AB
}

func (A Mat3x3[T]) Mulv(b Vec3[T]) Vec3[T] {
	var Ab Vec3[T]
	Ab[0] = 0 + *A.Index(0, 0)*b[0] + *A.Index(0, 1)*b[1] + *A.Index(0, 2)*b[2]
	Ab[1] = 0 + *A.Index(1, 0)*b[0] + *A.Index(1, 1)*b[1] + *A.Index(1, 2)*b[2]
	Ab[2] = 0 + *A.Index(2, 0)*b[0] + *A.Index(2, 1)*b[1] + *A.Index(2, 2)*b[2]
	return Ab
}

type Mat3x3U[T constraints.Float] [3 * (3 + 1) / 2]T

type Mat3x3Uf32 = Mat3x3U[float32]

func (A *Mat3x3U[T]) Index(i, j int) *T {
	A_i := A[len(A)-triangularNumber(3-i):][:3-i]
	A_i_j := &A_i[j-i]
	return A_i_j
}

func Mat3x3UOne[T constraints.Float]() Mat3x3U[T] {
	var I Mat3x3U[T]
	*I.Index(0, 0) = 1
	*I.Index(1, 1) = 1
	*I.Index(2, 2) = 1
	return I
}

func Mat3x3UDiag[T constraints.Float](d Vec3[T]) Mat3x3U[T] {
	var D Mat3x3U[T]
	*D.Index(0, 0) = d[0]
	*D.Index(1, 1) = d[1]
	*D.Index(2, 2) = d[2]
	return D
}

func (A Mat3x3U[T]) Inv() Mat3x3U[T] {
	panic("not implemented")
}

func (A Mat3x3U[T]) Mul(B Mat3x3U[T]) Mat3x3U[T] {
	var AB Mat3x3U[T]
	for i := range 3 {
		for k := i; k < 3; k++ {
			for j := k; j < 3; j++ {
				*AB.Index(i, k) += *A.Index(i, j) * *B.Index(j, k)
			}
		}
	}
	return AB
}

func (U Mat3x3U[T]) ToMat() Mat3x3[T] {
	var M Mat3x3[T]
	for i := range 3 {
		for j := i; j < 3; j++ {
			*M.Index(i, j) = *U.Index(i, j)
		}
	}
	return M
}

type Vec4[T constraints.Float] [4]T

type (
	Vec4f32 = Vec4[float32]
	Vec4f64 = Vec4[float64]
)

func (v Vec4[From]) Convert[To constraints.Float]() Vec4[To] {
	return Vec4[To]{
		To(v[0]),
		To(v[1]),
		To(v[2]),
		To(v[3]),
	}
}

func Vec4Ones[T constraints.Float]() Vec4[T] {
	return Vec4[T]{
		1,
		1,
		1,
		1,
	}
}

func (a Vec4[T]) Add(b Vec4[T]) Vec4[T] {
	return Vec4[T]{
		a[0] + b[0],
		a[1] + b[1],
		a[2] + b[2],
		a[3] + b[3],
	}
}

func (a Vec4[T]) Sub(b Vec4[T]) Vec4[T] {
	return Vec4[T]{
		a[0] - b[0],
		a[1] - b[1],
		a[2] - b[2],
		a[3] - b[3],
	}
}

func (a Vec4[T]) Scale(lambda T) Vec4[T] {
	return Vec4[T]{
		lambda * a[0],
		lambda * a[1],
		lambda * a[2],
		lambda * a[3],
	}
}

func (a Vec4[T]) Length() T {
	return T(math.Sqrt(float64(a.Dot(a))))
}

func (a Vec4[T]) Dot(b Vec4[T]) T {
	return 0 + a[0]*b[0] + a[1]*b[1] + a[2]*b[2] + a[3]*b[3]
}

func (v Vec4[T]) Normalize() Vec4[T] {
	lengthSqr := v.Dot(v)
	if !(lengthSqr > 0) {
		return Vec4[T]{}
	}
	length := T(math.Sqrt(float64(lengthSqr)))
	return Vec4[T]{
		v[0] / length,
		v[1] / length,
		v[2] / length,
		v[3] / length,
	}
}

// TODO: kill this
func (a Vec4[T]) Lerp(b Vec4[T], t T) Vec4[T] {
	return Vec4[T]{
		lerp(a[0], b[0], t),
		lerp(a[1], b[1], t),
		lerp(a[2], b[2], t),
		lerp(a[3], b[3], t),
	}
}

type Mat4x4[T constraints.Float] [4 * 4]T

type Mat4x4f32 = Mat4x4[float32]

func (M Mat4x4[From]) Convert[To constraints.Float]() Mat4x4[To] {
	var M2 Mat4x4[To]
	for i, v := range M {
		M2[i] = To(v)
	}
	return M2
}

func (A *Mat4x4[T]) Index(i, j int) *T {
	A_i := A[i*4:][:4]
	A_i_j := &A_i[j]
	return A_i_j
}

func Mat4x4One[T constraints.Float]() Mat4x4[T] {
	var I Mat4x4[T]
	*I.Index(0, 0) = 1
	*I.Index(1, 1) = 1
	*I.Index(2, 2) = 1
	*I.Index(3, 3) = 1
	return I
}

func Mat4x4Diag[T constraints.Float](d Vec4[T]) Mat4x4[T] {
	var D Mat4x4[T]
	*D.Index(0, 0) = d[0]
	*D.Index(1, 1) = d[1]
	*D.Index(2, 2) = d[2]
	*D.Index(3, 3) = d[3]
	return D
}

func (A Mat4x4[T]) Inv() Mat4x4[T] {
	panic("not implemented")
}

func (A Mat4x4[T]) Mul(B Mat4x4[T]) Mat4x4[T] {
	var AB Mat4x4[T]
	*AB.Index(0, 0) = 0 + *A.Index(0, 0)**B.Index(0, 0) + *A.Index(0, 1)**B.Index(1, 0) + *A.Index(0, 2)**B.Index(2, 0) + *A.Index(0, 3)**B.Index(3, 0)
	*AB.Index(0, 1) = 0 + *A.Index(0, 0)**B.Index(0, 1) + *A.Index(0, 1)**B.Index(1, 1) + *A.Index(0, 2)**B.Index(2, 1) + *A.Index(0, 3)**B.Index(3, 1)
	*AB.Index(0, 2) = 0 + *A.Index(0, 0)**B.Index(0, 2) + *A.Index(0, 1)**B.Index(1, 2) + *A.Index(0, 2)**B.Index(2, 2) + *A.Index(0, 3)**B.Index(3, 2)
	*AB.Index(0, 3) = 0 + *A.Index(0, 0)**B.Index(0, 3) + *A.Index(0, 1)**B.Index(1, 3) + *A.Index(0, 2)**B.Index(2, 3) + *A.Index(0, 3)**B.Index(3, 3)
	*AB.Index(1, 0) = 0 + *A.Index(1, 0)**B.Index(0, 0) + *A.Index(1, 1)**B.Index(1, 0) + *A.Index(1, 2)**B.Index(2, 0) + *A.Index(1, 3)**B.Index(3, 0)
	*AB.Index(1, 1) = 0 + *A.Index(1, 0)**B.Index(0, 1) + *A.Index(1, 1)**B.Index(1, 1) + *A.Index(1, 2)**B.Index(2, 1) + *A.Index(1, 3)**B.Index(3, 1)
	*AB.Index(1, 2) = 0 + *A.Index(1, 0)**B.Index(0, 2) + *A.Index(1, 1)**B.Index(1, 2) + *A.Index(1, 2)**B.Index(2, 2) + *A.Index(1, 3)**B.Index(3, 2)
	*AB.Index(1, 3) = 0 + *A.Index(1, 0)**B.Index(0, 3) + *A.Index(1, 1)**B.Index(1, 3) + *A.Index(1, 2)**B.Index(2, 3) + *A.Index(1, 3)**B.Index(3, 3)
	*AB.Index(2, 0) = 0 + *A.Index(2, 0)**B.Index(0, 0) + *A.Index(2, 1)**B.Index(1, 0) + *A.Index(2, 2)**B.Index(2, 0) + *A.Index(2, 3)**B.Index(3, 0)
	*AB.Index(2, 1) = 0 + *A.Index(2, 0)**B.Index(0, 1) + *A.Index(2, 1)**B.Index(1, 1) + *A.Index(2, 2)**B.Index(2, 1) + *A.Index(2, 3)**B.Index(3, 1)
	*AB.Index(2, 2) = 0 + *A.Index(2, 0)**B.Index(0, 2) + *A.Index(2, 1)**B.Index(1, 2) + *A.Index(2, 2)**B.Index(2, 2) + *A.Index(2, 3)**B.Index(3, 2)
	*AB.Index(2, 3) = 0 + *A.Index(2, 0)**B.Index(0, 3) + *A.Index(2, 1)**B.Index(1, 3) + *A.Index(2, 2)**B.Index(2, 3) + *A.Index(2, 3)**B.Index(3, 3)
	*AB.Index(3, 0) = 0 + *A.Index(3, 0)**B.Index(0, 0) + *A.Index(3, 1)**B.Index(1, 0) + *A.Index(3, 2)**B.Index(2, 0) + *A.Index(3, 3)**B.Index(3, 0)
	*AB.Index(3, 1) = 0 + *A.Index(3, 0)**B.Index(0, 1) + *A.Index(3, 1)**B.Index(1, 1) + *A.Index(3, 2)**B.Index(2, 1) + *A.Index(3, 3)**B.Index(3, 1)
	*AB.Index(3, 2) = 0 + *A.Index(3, 0)**B.Index(0, 2) + *A.Index(3, 1)**B.Index(1, 2) + *A.Index(3, 2)**B.Index(2, 2) + *A.Index(3, 3)**B.Index(3, 2)
	*AB.Index(3, 3) = 0 + *A.Index(3, 0)**B.Index(0, 3) + *A.Index(3, 1)**B.Index(1, 3) + *A.Index(3, 2)**B.Index(2, 3) + *A.Index(3, 3)**B.Index(3, 3)
	return AB
}

func (A Mat4x4[T]) Mulv(b Vec4[T]) Vec4[T] {
	var Ab Vec4[T]
	Ab[0] = 0 + *A.Index(0, 0)*b[0] + *A.Index(0, 1)*b[1] + *A.Index(0, 2)*b[2] + *A.Index(0, 3)*b[3]
	Ab[1] = 0 + *A.Index(1, 0)*b[0] + *A.Index(1, 1)*b[1] + *A.Index(1, 2)*b[2] + *A.Index(1, 3)*b[3]
	Ab[2] = 0 + *A.Index(2, 0)*b[0] + *A.Index(2, 1)*b[1] + *A.Index(2, 2)*b[2] + *A.Index(2, 3)*b[3]
	Ab[3] = 0 + *A.Index(3, 0)*b[0] + *A.Index(3, 1)*b[1] + *A.Index(3, 2)*b[2] + *A.Index(3, 3)*b[3]
	return Ab
}

type Affine3[T constraints.Float] struct {
	M Mat3x3f32
	T Vec3[T]
}

type (
	Affine3f32 = Affine3[float32]
	Affine3f64 = Affine3[float64]
)

func (A Affine3[From]) Convert[To constraints.Float]() Affine3[To] {
	return Affine3[To]{
		M: A.M,
		T: A.T.Convert[To](),
	}
}

func Affine3One[T constraints.Float]() Affine3[T] {
	return Affine3[T]{
		M: Mat3x3One[float32](),
	}
}

/*
func (A Affine3[T]) Inv() Affine3[T] {
	panic("not implemented")
}
*/

func (A Affine3[T]) Mul(B Affine3[T]) Affine3[T] {
	return Affine3[T]{
		M: A.M.Mul(B.M),
		T: A.T.Add(A.M.Convert[T]().Mulv(B.T)),
	}
}

func (A Affine3[T]) TRS() TRS3[T] {
	// TODO: don't assume this is just translation * rotation, properly extract
	// shcale too or at least scale with scale.
	Q := A.M
	R := Mat3x3UOne[float32]()

	return TRS3[T]{
		T: A.T,
		R: Rot3FromMat(Q),
		S: R,
	}
}

type TRS3[T constraints.Float] struct {
	T Vec3[T]
	R Rot3
	S Mat3x3Uf32
}

type (
	TRS3f32 = TRS3[float32]
	TRS3f64 = TRS3[float64]
)

func TRS3One[T constraints.Float]() TRS3[T] {
	return TRS3[T]{
		R: Rot3One(),
		S: Mat3x3UOne[float32](),
	}
}

func (trs TRS3[T]) Compose() Affine3[T] {
	return Affine3[T]{
		// TODO: special case R.Mat() by S.Mat() for more :b:erf and kill those
		// methods
		M: trs.R.ToMat().Mul(trs.S.ToMat()),
		T: trs.T,
	}
}
